version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      astro:
        patterns: ['astro', '@astrojs/*']
      tooling:
        patterns:
          [
            'eslint*',
            '@eslint/*',
            'typescript-eslint',
            'prettier*',
            'vitest',
            '@playwright/test',
            '@axe-core/*',
          ]
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
